package goydb

import (
	"context"
	"encoding/hex"
	"flag"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/caarlos0/env/v6"
	gorilla_handlers "github.com/gorilla/handlers"
	"github.com/gorilla/mux"
	"github.com/gorilla/sessions"
	adapterlogger "github.com/goydb/goydb/internal/adapter/logger"
	"github.com/goydb/goydb/internal/adapter/storage"
	"github.com/goydb/goydb/internal/adapter/view/gojaview"
	"github.com/goydb/goydb/internal/adapter/view/tengoview"
	"github.com/goydb/goydb/internal/controller"
	"github.com/goydb/goydb/internal/handler"
	"github.com/goydb/goydb/internal/service"
	"github.com/goydb/goydb/pkg/model"
	"github.com/goydb/goydb/pkg/public"
)

type Config struct {
	// DatabaseDir directory path where the databases and
	// attachments should be stored
	DatabaseDir string `env:"GOYDB_DB_DIR" envDefault:"./dbs"`
	// PublicDir the public directory that should be served by
	// the default server implementation
	PublicDir string `env:"GOYDB_PUBLIC" envDefault:"./public"`
	// EnablePublicDir allows to enable/disable the public directory serving
	EnablePublicDir bool `env:"GOYDB_ENABLE_PUBLIC" envDefault:"true"`
	// ListenAddress contains the default address to listen to.
	// Not respected if the server is generated by the user.
	ListenAddress string `env:"GOYDB_LISTEN" envDefault:":7070"`
	// CookieSecret a secret that is used to verify the
	// integrity, usually generated using openssl rand -hex 32
	CookieSecret string `env:"GOYDB_SECRET" envDefault:"21ccf11d067cec8eebd663af3dc8785521d1cc366f0d533e6740c1cb6840dceb"`
	// Aministrators list of username:password sperated by ","
	// for multiple users
	Aministrators string `env:"GOYDB_ADMINS" envDefault:"admin:secret"`
	// Containers are zip file based containers that should be mounted before the
	// database application
	Containers []public.Container
}

// NewConfig will create a new configuration
// based on the given environment values.
// Errors while parsing the environment are returned.
func NewConfig() (*Config, error) {
	cfg := Config{}
	if err := env.Parse(&cfg); err != nil {
		return nil, fmt.Errorf("error parsing the environment config: %v", err)
	}
	return &cfg, nil
}

// ParseFlags to change the configuration
func (c *Config) ParseFlags() {
	flag.StringVar(&c.DatabaseDir, "dbs", c.DatabaseDir, "directory with databases")
	flag.StringVar(&c.PublicDir, "public", c.PublicDir, "directory public data")
	flag.StringVar(&c.ListenAddress, "addr", c.ListenAddress, "listening address")
	flag.StringVar(&c.CookieSecret, "cookie-secret", c.CookieSecret, "secret for the cookies")
	flag.StringVar(&c.Aministrators, "admins", c.Aministrators, "admins for the databases")

	flag.Parse()
}

// BuildDatabase builds the storage and http handler based
// on the given configuration.
func (c *Config) BuildDatabase() (*Goydb, error) {
	var gdb Goydb

	secret, err := hex.DecodeString(c.CookieSecret)
	if err != nil {
		return nil, fmt.Errorf("failed to decode cookie secret: %w", err)
	}
	store := sessions.NewCookieStore(secret)

	admins, err := model.ParseAdmins(c.Aministrators)
	if err != nil {
		return nil, fmt.Errorf("failed to parse admins: %w", err)
	}

	// Create the config store early so we can read it for logger config.
	configPath := filepath.Join(c.DatabaseDir, "_config.json")
	cs := handler.NewConfigStore(configPath, nil) // Pass nil logger for now, will be updated in task #7

	// Create logger from config BEFORE storage
	logger, err := adapterlogger.NewFromConfig(cs.Get)
	if err != nil {
		return nil, fmt.Errorf("failed to create logger: %w", err)
	}
	gdb.Logger = logger

	// Open storage with logger
	s, err := storage.Open(
		c.DatabaseDir,
		storage.WithLogger(logger.With("component", "storage")),
		storage.WithViewEngine("", gojaview.NewViewServer), // default langage
		storage.WithViewEngine("javascript", gojaview.NewViewServer),
		storage.WithViewEngine("tengo", tengoview.NewViewServer),
		storage.WithFilterEngine("", gojaview.NewFilterServer),
		storage.WithFilterEngine("javascript", gojaview.NewFilterServer),
		storage.WithFilterEngine("tengo", tengoview.NewFilterServer),
		storage.WithReducerEngine("", gojaview.NewReducerBuilder(logger.With("component", "reducer"))),
		storage.WithReducerEngine("javascript", gojaview.NewReducerBuilder(logger.With("component", "reducer"))),
		storage.WithValidateEngine("", gojaview.NewValidateServerBuilder(logger.With("component", "validate"))),
		storage.WithValidateEngine("javascript", gojaview.NewValidateServerBuilder(logger.With("component", "validate"))),
		storage.WithValidateEngine("tengo", tengoview.NewValidateServerBuilder(logger.With("component", "validate"))),
		storage.WithUpdateEngine("", gojaview.NewUpdateServer),
		storage.WithUpdateEngine("javascript", gojaview.NewUpdateServer),
		storage.WithUpdateEngine("tengo", tengoview.NewUpdateServer),
	)
	if err != nil {
		return nil, fmt.Errorf("failed to open database dir: %w", err)
	}

	if err := s.EnsureSystemDatabases(context.Background()); err != nil {
		return nil, fmt.Errorf("failed to ensure system databases: %w", err)
	}

	tc := controller.Task{
		Storage: s,
		Logger:  logger.With("component", "task"),
	}
	go tc.Run(context.Background())
	replication := &service.Replication{
		Storage: s,
		Logger:  logger.With("component", "replication"),
	}
	go replication.Run(context.Background())
	gdb.Storage = s
	gdb.Config = cs

	r := mux.NewRouter()
	for _, c := range c.Containers {
		err = public.MountContainer(r, c)
		if err != nil {
			logger.Warnf(context.Background(), "container mount failed", "container", c.FolderName(), "error", err)
		}
	}
	gdb.Handler = r

	if c.EnablePublicDir {
		err := public.Public{Dir: c.PublicDir}.Mount(r)
		if err != nil {
			return nil, fmt.Errorf("failed to mount public dir: %w", err)
		}
	}

	err = handler.Router{
		SessionStore: store,
		Storage:      s,
		Admins:       admins,
		Config:       cs,
		Replication:  replication,
		Logger:       logger,
	}.Build(r)
	if err != nil {
		return nil, fmt.Errorf("failed to build router: %w", err)
	}

	// Apply CORS middleware if configured.
	if enable, _ := cs.Get("httpd", "enable_cors"); enable == "true" {
		opts := buildCORSOpts(cs)
		gdb.Handler = gorilla_handlers.CORS(opts...)(gdb.Handler)
	}

	return &gdb, nil
}

func buildCORSOpts(cs *handler.ConfigStore) []gorilla_handlers.CORSOption {
	var opts []gorilla_handlers.CORSOption
	if origins, ok := cs.Get("cors", "origins"); ok && origins != "" {
		opts = append(opts, gorilla_handlers.AllowedOrigins(splitTrim(origins)))
	}
	if methods, ok := cs.Get("cors", "methods"); ok && methods != "" {
		opts = append(opts, gorilla_handlers.AllowedMethods(splitTrim(methods)))
	}
	if hdrs, ok := cs.Get("cors", "headers"); ok && hdrs != "" {
		opts = append(opts, gorilla_handlers.AllowedHeaders(splitTrim(hdrs)))
	}
	if creds, _ := cs.Get("cors", "credentials"); creds == "true" {
		opts = append(opts, gorilla_handlers.AllowCredentials())
	}
	return opts
}

// splitTrim splits a comma-separated string and trims whitespace from each part.
func splitTrim(s string) []string {
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if t := strings.TrimSpace(p); t != "" {
			out = append(out, t)
		}
	}
	return out
}
